
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: db
  selector:
    app: db
  
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
  labels:
    app: words-db
spec:
  template:
    metadata:
      labels:
        app: words-db
    spec:
      containers:
      - name: db
        image: 321455566/db:master
        ports:
        - containerPort: 5432
          name: db
---
apiVersion: v1
kind: Service
metadata:
  name: words
  labels:
    app: words
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: words
  selector:
    app: words
  
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: words
  labels:
    app: words
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: words
    spec:
      containers:
      - name: words
        image: 321455566/words:master
        ports:
        - containerPort: 8080
          name: words
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  ports:
    - port: 8081
      targetPort: 80
      name: web
  selector:
    app: web
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: 321455566/web:${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}
        ports:
        - containerPort: 80
          name: web
