apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: db
  selector:
    app: db
    
---

apiVersion: v1
kind: Service
metadata:
  name: words
  labels:
    app: words
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: words
  selector:
    app: words

---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  ports:
    - port: 8081
      targetPort: 80
      name: web
  selector:
    app: web
  type: LoadBalancer
